version: '2'
services:
  concourse-db:
    image: postgres:9.5
    labels:
      io.rancher.container.hostname_override: container_name
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /database

  concourse-keys-datavolume:
    image: alpine
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
    volumes:
      - keys:/var/keys
    command: sh -c "apk --update add openssh &&
      rm -rf /var/cache/apk/* &&
      mkdir -p /var/keys/web /var/keys/worker &&
      ssh-keygen -t rsa -f /var/keys/web/tsa_host_key -N '' &&
      ssh-keygen -t rsa -f /var/keys/web/session_signing_key -N '' &&
      ssh-keygen -t rsa -f /var/keys/worker/worker_key -N '' &&
      cp /var/keys/worker/worker_key.pub /var/keys/web/authorized_worker_keys &&
      cp /var/keys/web/tsa_host_key.pub /var/keys/worker"

  concourse-web:
    image: concourse/concourse:3.5.0
    labels:
      io.rancher.container.hostname_override: container_name
    command: web
    depends_on:
      - concourse-keys-datavolume
    links:
      - concourse-keys-datavolume
    volumes:
      - keys:/var/keys
    ports: 
      - "${CONCOURSE_PORT}:8080"
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: ${CONCOURSE_USERNAME}
      CONCOURSE_BASIC_AUTH_PASSWORD: ${CONCOURSE_PASSWORD}
      CONCOURSE_DEVELOPMENT_MODE: 'true'
      CONCOURSE_EXTERNAL_URL: "http://${CONCOURSE_FQDN}:${CONCOURSE_PORT}"
      CONCOURSE_TSA_HOST_KEY: "/var/keys/web/tsa_host_key"
      CONCOURSE_TSA_AUTHORIZED_KEYS: "/var/keys/web/authorized_worker_keys"
      CONCOURSE_SESSION_SIGNING_KEY: "/var/keys/web/session_signing_key"
      CONCOURSE_POSTGRES_DATA_SOURCE: |-
        postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@concourse-db:5432/concourse?sslmode=disable

  concourse-worker:
    image: concourse/concourse:3.5.0
    privileged: true
    cap_add:
      - ALL
    labels:
      io.rancher.container.hostname_override: container_name
    depends_on:
      - concourse-keys-datavolume
    links:
      - concourse-keys-datavolume
    volumes:
      - keys:/var/keys
    command: worker
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_TSA_PUBLIC_KEY: "/var/keys/worker/tsa_host_key.pub"
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: "/var/keys/worker/worker_key"

volumes:
  keys:
